export const stage = {
    pages: [
        {
            id: 'page1',
            imgSrc: '',
            children: [
                {
                    id: '4ad914d5-69c6-4025-b10b-c541d473e926',
                    text: 'Label1',
                    type: 'LABEL',
                    position: { x: 71.81909547738692, y: 46.91637010676157 },
                    width: 90,
                    height: 16,
                    fontFamily: 'MS Gothic',
                    fontSize: 11,
                    color: 'white',
                    bold: false,
                    italics: false,
                    underline: false,
                    backgroundColor: '#8c8c8c',
                    borderOrNot: false,
                    borderType: 'solid',
                    borderColor: '#000000',
                    borderWidth: 1,
                    url: '',
                    align: 'left',
                    verticalAlign: 'middle',
                    visible: true,
                    enable: true,
                },
                {
                    id: '54519077-cb19-4ed9-a3b2-db7de38553a4',
                    text: 'TextBox1',
                    position: { x: 92.76633165829145, y: 112.79893238434164 },
                    width: 90,
                    height: 16,
                    fontFamily: 'MS Gothic',
                    fontSize: 11,
                    color: '#000000',
                    bold: false,
                    italics: false,
                    backgroundColor: '#FFFFFF',
                    borderOrNot: false,
                    borderType: 'solid',
                    borderColor: '#000000',
                    borderWidth: 1,
                    password: false,
                    placeHolder: '',
                    tooltip: '',
                    align: 'left',
                    verticalAlign: 'middle',
                    visible: true,
                    enable: true,
                    maxLength: 100,
                    type: 'textbox',
                },
                {
                    id: '80d0dc43-2cd0-4f00-9896-3981ce375b76',
                    text: 'CheckBox1',
                    position: { x: 93.76381909547737, y: 181.6761565836299 },
                    width: 90,
                    height: 22,
                    fontFamily: 'MS Gothic',
                    fontSize: 11,
                    color: '#000000',
                    bold: false,
                    italics: false,
                    backgroundColor: '#FFFFFF',
                    borderOrNot: false,
                    borderType: 'solid',
                    borderColor: '#000000',
                    borderWidth: 1,
                    tooltip: '',
                    align: 'left',
                    verticalAlign: 'middle',
                    checked: true,
                    visible: true,
                    enable: true,
                    type: 'checkbox',
                },
                {
                    id: '188c8d18-2534-4921-b4af-c5a22cc78f3f',
                    text: 'Radio1',
                    position: { x: 110.72110552763819, y: 257.5409252669039 },
                    width: 90,
                    height: 16,
                    fontFamily: 'MS Gothic',
                    fontSize: 11,
                    color: '#000000',
                    bold: false,
                    italics: false,
                    backgroundColor: '#FFFFFF',
                    borderOrNot: false,
                    borderType: 'solid',
                    borderColor: '#000000',
                    borderWidth: 1,
                    tooltip: '',
                    align: 'left',
                    verticalAlign: 'middle',
                    checked: false,
                    radioGroup: 'female',
                    visible: false,
                    enable: true,
                    type: 'radio',
                },
                {
                    id: '3319b203-68da-4793-bf5a-0f66675b78eb',
                    text: '- select -',
                    position: { x: 124.6859296482412, y: 312.4430604982207 },
                    width: 110,
                    height: 20,
                    fontFamily: 'MS Gothic',
                    fontSize: 11,
                    color: '#000000',
                    bold: false,
                    italic: false,
                    backgroundColor: '#FFFFFF',
                    borderOrNot: true,
                    borderType: 'solid',
                    borderColor: '#000000',
                    borderWidth: 1,
                    tooltip: '',
                    align: 'center',
                    verticalAlign: 'middle',
                    visible: true,
                    enable: true,
                    type: 'combobox',
                },
                {
                    id: 'b0d82e5a-9a2e-4c81-a3fc-475ef5902c83',
                    text: 'ListBox1',
                    position: { x: 137.65326633165827, y: 388.3078291814947 },
                    width: 90,
                    height: 60,
                    fontFamily: 'MS Gothic',
                    fontSize: 11,
                    color: '#000000',
                    bold: false,
                    italics: false,
                    backgroundColor: '#FFFFFF',
                    borderOrNot: true,
                    borderType: 'solid',
                    borderColor: '#000000',
                    borderWidth: 1,
                    tooltip: '',
                    align: 'center',
                    verticalAlign: 'middle',
                    visible: true,
                    enable: true,
                    type: 'listbox',
                },
                {
                    id: '7f01e286-b723-49aa-ad14-72ed45b8f589',
                    text: 'signature1',
                    position: { x: 146.63065326633165, y: 492.1227758007118 },
                    borderRadius: 50,
                    borderWidth: 1,
                    color: '#FF0000',
                    borderOrNot: false,
                    borderColor: '#FF0000',
                    borderType: 'solid',
                    backgroundColor: '#FFFFFF',
                    visible: true,
                    boxSizing: 'border-box',
                    width: 76,
                    height: 76,
                    fontFamily: 'MS Gothic',
                    fontSize: 9,
                    bold: false,
                    italic: false,
                    fill: '#ddd',
                    horizontalAlign: 'center',
                    type: 'signature',
                },
                {
                    id: '0d5f124a-5fbe-4f1d-ba4f-9e1103612a3f',
                    text: 'Grid1',
                    type: 'grid',
                    position: { x: 165.5829145728643, y: 673.7989323843417 },
                    width: 90,
                    height: 16,
                    fontFamily: 'MS Gothic',
                    fontSize: 11,
                    color: '#000000',
                    bold: false,
                    italics: false,
                    backgroundColor: '#8c8c8c',
                    borderOrNot: false,
                    borderType: 'solid',
                    borderColor: 'black',
                    borderWidth: 1,
                    numRows: 2,
                    numCols: 2,
                    headerText: ['header 1', 'header2'],
                    headerHeight: 25,
                    rowHeight: 35,
                    align: 'left',
                    verticalAlign: 'middle',
                    rowData: [
                        {
                            id: 'label11',
                            text: '申請日',
                            type: 'LABEL',
                            position: { x: 50, y: 120 },
                            width: 80,
                            height: 22,
                            fontFamily: 'MS Gothic',
                            fontSize: 11,
                            color: '#ffffff',
                            bold: false,
                            italics: false,
                            underline: false,
                            backgroundColor: '#8c8c8c',
                            borderOrNot: true,
                            borderType: 'solid',
                            borderColor: '#c7c6c6',
                            borderWidth: 1,
                            url: '',
                            align: 'center',
                            verticalAlign: 'middle',
                            visible: true,
                            enable: true,
                        },
                        {
                            id: 'textbox11',
                            text: '',
                            position: { x: 129, y: 139 },
                            width: 120,
                            height: 22,
                            fontFamily: 'MS Gothic',
                            fontSize: 11,
                            color: '#000000',
                            bold: false,
                            italics: false,
                            backgroundColor: 'white',
                            borderOrNot: false,
                            borderType: 'solid',
                            borderColor: '#000000',
                            borderWidth: 1,
                            password: false,
                            placeHolder: '申請日を入れて',
                            tooltip: '',
                            align: 'left',
                            verticalAlign: 'middle',
                            visible: true,
                            enable: true,
                            maxLength: 100,
                            type: 'textbox',
                        },
                    ],
                    visible: true,
                    enable: true,
                },
            ],
        },
        {
            id: 'page2',
            imgSrc: '',
            children: [],
        },
    ],
    pageNo: 2,
    controlNo: 1,
    sizeKonva: { width: 794, height: 1122 },
}
